### ISSUE TITLE
Change to <inheritdoc /> only if the xml documentation is the same

### ISSUE THREAD

**Issue by icnocop** [someguy20336/PullThroughDoc#18]
Hi.

Thank you for PullThroughDoc.

I'd like to request the ability to `Change to <inheritdoc />` only if the xml documentation is the same as the base class.

In this way, I can be certain not to lose any documentation.

Thank you.

**Comment by someguy20336** [comment]
Hey thanks for the suggestion!  I have a couple of questions:

1. Couldn't there be a use case where someone wants to legitimately do this?  Wouldn't this break that?  How would you suggest we handle that case?
2. In the case that they aren't the same, why are you attempting to use the code fix in the first place?

**Comment by icnocop** [comment]
> Couldn't there be a use case where someone wants to legitimately do this?

Yes, I could imagine a user wants to `Change to <inheritdocs />`, even when the documentation is different.

> Wouldn't this break that?

It depends on how this feature is implemented.

> How would you suggest we handle that case?

I've seen code analyzers suggest code fixes with multiple options.

For example:
1. If the XML documentation is the same, only display one `Change to <inheritdoc />` option, like it is now.
2. If the XML documentation is different, display two options:
a. `Change to <inheritdoc />`
    This will overwrite the XML documentation of the current/active property with `<inheritdoc />` as it does now.
b. `Change to <inheritdoc /> and use this documentation`
    This will replace the parent property's documentation with the XML documentation of the current/active property and then overwrite the XML documentation of the current/active property with `<inheritdoc />`.
    I don't know if it's possible to show the changes to the parent property in the quick preview window or not, but that could also help the user decide which XML documentation to use without having to navigate to the parent property.
    Otherwise, maybe a preview changes window would be helpful.

Example code fix with multiple options:
![image](https://github.com/someguy20336/PullThroughDoc/assets/507649/d68b47bf-0aab-451b-a08f-70f5bc578637)

Example preview window:
![image](https://github.com/someguy20336/PullThroughDoc/assets/507649/5bb83b6a-2886-4d31-abe0-0687417093f6)


> In the case that they aren't the same, why are you attempting to use the code fix in the first place?

To eliminate duplicate, and possibly conflicting, documentation.

For example, someone updated the XML documentation in one place but not the other.

Otherwise, if someone needs to update the documentation in the future, they don't have to determine if the property is inherited first in order to make a decision on where/how to update the documentation.

Thank you.

**Comment by someguy20336** [comment]
Ah, interesting suggestion. I think that could make sense then - I'll have to look into the options. 

I don't know how simple changing the parent would be since it is likely in another document, so one option could be to just make it more apparent that the documentation is different between the two like I think you hinted at. But I'll have to play around with it

**Comment by someguy20336** [comment]
ok, took a quick look at this - it looks like it is possible to register a code fix that could affect a solution, meaning presumably you could have a code fix that affects another document. 

So now just to triple check I understand the request - let's say I had the following in two separate documents:

```csharp
// In one file
public class BaseClass
{
    /// <summary>Does things</summary>
    public abstract void MethodOne();
}

// In another file
public class DerivedClass : BaseClass
{
   /// <summary>Not the same as the parent</summary>
   public override void MethodOne() { }
}

```

The expected behavior you are suggesting might be that if you look at the code fixes for `DerivedClass.MethodOne`, you might see:
- `Replace with <inheritdoc />`
  - This does what it does today and replaces `DerivedClass.MethodOne` with `<inheritdoc />`.  The original doc from `DeriviedClass.MethodOne` is lost
- Maybe something like `Set as parent documentation` (not wild about that name, but whatever for now).  This would:
  - Set `BaseClass.MethodOne` to `<summary>Not the same as the parent</summary>`
  - Set `DerivedClass.MethodOne` to `<inheritdoc />`

The classes after this new code fix might look like this:
```csharp
// In one file
public class BaseClass
{
   /// <summary>Not the same as the parent</summary>
    public abstract void MethodOne();
}

// In another file
public class DerivedClass : BaseClass
{
   /// <inheritdoc />
   public override void MethodOne() { }
}

```

Does that match your expectation there?

**Comment by icnocop** [comment]
> Does that match your expectation there?

Yes, perfectly.

Thank you!

**Comment by someguy20336** [comment]
Sorry - this has taken forever to get to, but I should have this out for you soon! Finally got some time to knock this out.
