### ISSUE TITLE
Support pulling through documentation from external libraries

### ISSUE THREAD

**Issue by Hefaistos68** [someguy20336/PullThroughDoc#9]
As seen on this screenshot, this is an overridden method from the System.Windows.Form class, to begin with, no "pull through" menu item was available, after inserting manually the documentation comment, no "switch to" menu entry is available.
Havent seen a pattern, it just happens sometimes.
![image](https://user-images.githubusercontent.com/8855055/108393784-ea893780-720b-11eb-8a48-9e17982376ba.png)

VS2019 16.8.4

**Comment by someguy20336** [comment]
This kind of sounds like #1 (which ultimately is a known limitation so I closed it).  Currently, the base member needs to be in the same solution (i.e. you have the source code for that member).  When the base member (such as `Form.Refresh`) is part of an external library, I don't currently pull that one in.  There are some complications that I haven't gotten around to looking into yet (mostly figuring out where that documentation actually lives).

I am thinking we rename this to "support documentation from external libraries" if that turns out to be what you are experiencing.  Can you verify?

**Comment by Hefaistos68** [comment]
Will check, but if i am not mistaken it happened with solution classes too. But let me check tomorrow.

**Comment by Hefaistos68** [comment]
Seems to be related to external classes only. Will update if I encounter any other cases.

**Comment by someguy20336** [comment]
Ok - updating the name.  This is something I want to look at soon, so I will keep this issue open.
